#!/usr/bin/env node
/**
 * Generate the built-in procedural mesh OBJ files.
 *
 * This script owns no geometry of its own: every shape comes from
 * shaders/src/geometry/primitives.js, the same generators the scene graph
 * uses. This file is only CLI handling, OBJ serialization, and file writing.
 *
 * Face winding: primitives.js emits counter-clockwise triangles relative to
 * their outward normals, and runtime/obj-parser.js reverses face order when it
 * reads a file ("OBJ CW to OpenGL CCW"). So faces are written in reverse index
 * order here, which lands back at CCW-front on the GPU where the backend culls
 * back faces.
 *
 * Usage:
 *   node share/meshes/generate.cjs [--out <dir>]
 *
 * --out defaults to this script's directory (the committed assets).
 */
const fs = require('fs')
const path = require('path')
const { pathToFileURL } = require('url')

const PRIMITIVES = path.resolve(
    __dirname, '..', '..', 'shaders', 'src', 'geometry', 'primitives.js'
)

// Parameters chosen so each mesh keeps the extents the committed assets have
// always had: everything fits inside a unit cube centered on the origin.
function meshRecipes(p) {
    return {
        cube: () => p.createBox({ size: [1, 1, 1] }),
        sphere: () => p.createSphere({ radius: 0.5, segments: 32 }),
        torus: () => p.createTorus({ radius: 0.35, tube: 0.15, segments: 32, tubeSegments: 16 }),
        cylinder: () => p.createCylinder({ radius: 0.4, height: 1, segments: 32 }),
        cone: () => p.createCone({ radius: 0.4, height: 1, segments: 32 }),
        capsule: () => p.createCapsule({ radius: 0.25, height: 1.1, segments: 32, rings: 8 }),
        icosphere: () => p.createIcosphere({ radius: 0.5, subdivisions: 2 })
    }
}

/**
 * Serialize an indexed Geometry to Wavefront OBJ text.
 * Positions, UVs and normals share one index space, so every face vertex is
 * written as `i/i/i`.
 * @param {{positions: Float32Array, normals: Float32Array, uvs: Float32Array, indices: Uint32Array}} geo
 * @param {string} name
 * @returns {string}
 */
function toOBJ(geo, name) {
    const { positions, normals, uvs, indices } = geo
    const lines = [`# ${name} — generated by share/meshes/generate.cjs from shaders/src/geometry/primitives.js`]
    const f = (n) => n.toFixed(6)

    for (let i = 0; i < positions.length; i += 3) {
        lines.push(`v ${f(positions[i])} ${f(positions[i + 1])} ${f(positions[i + 2])}`)
    }
    for (let i = 0; i < uvs.length; i += 2) {
        lines.push(`vt ${f(uvs[i])} ${f(uvs[i + 1])}`)
    }
    for (let i = 0; i < normals.length; i += 3) {
        lines.push(`vn ${f(normals[i])} ${f(normals[i + 1])} ${f(normals[i + 2])}`)
    }
    for (let i = 0; i < indices.length; i += 3) {
        // Reverse order: obj-parser flips face winding on read
        const a = indices[i] + 1
        const b = indices[i + 1] + 1
        const c = indices[i + 2] + 1
        lines.push(`f ${a}/${a}/${a} ${c}/${c}/${c} ${b}/${b}/${b}`)
    }

    return lines.join('\n') + '\n'
}

function parseArgs(argv) {
    let outDir = __dirname
    for (let i = 0; i < argv.length; i++) {
        if (argv[i] === '--out') {
            outDir = argv[i + 1]
            if (!outDir) throw new Error('--out requires a directory')
            i++
        } else {
            throw new Error(`unknown argument: ${argv[i]}`)
        }
    }
    return { outDir: path.resolve(outDir) }
}

async function main() {
    const { outDir } = parseArgs(process.argv.slice(2))
    const primitives = await import(pathToFileURL(PRIMITIVES).href)

    fs.mkdirSync(outDir, { recursive: true })

    for (const [name, build] of Object.entries(meshRecipes(primitives))) {
        const geo = build()
        const obj = toOBJ(geo, name)
        fs.writeFileSync(path.join(outDir, `${name}.obj`), obj)
        console.log(`${name}.obj: ${geo.positions.length / 3} vertices, ${geo.indices.length / 3} faces`)
    }
}

main().catch((err) => {
    console.error(err.message)
    process.exit(1)
})
